SELECT 
	B.service_id,
	A.created_date,
	A.order_id,
	A.order_type,
	B.sub_order_state,
	B.state_reason,
	"Raised to NCC" As "Raised To",
	"Asnake" As "SPOC",
	"" As "Comments"
FROM
	COM_ORDER_MASTER PARTITION(p7) A,
	COM_SUB_ORDER_DETAILS PARTITION(p7) B
WHERE
	A.order_id = '1262325984393613312' AND A.order_id = B.ORDER_ID
ORDER BY
	A.CREATED_DATE;





SELECT
	B.SUB_ORDER_ID,
	A.order_id,
	B.service_id,
	A.order_type,
	B.sub_order_state,
	B.state_reason,
	A.created_date,
	A.CHANNEL
FROM
	COM_ORDER_MASTER A,
	COM_SUB_ORDER_DETAILS B
WHERE
	A.order_id = B.order_id
	AND A.ORDER_TYPE IN ('ConnectionMigration', 'AddService', 'Onboarding', 'ChangeSim','AdjustMainAccount', 'ChangeSubscription') 
	AND A.ORDER_STATE != 'Completed'
	and A.CREATED_DATE BETWEEN '2024-01-05 00:00:00' and now()
	AND A.ORDER_ID IN ('1256125438257336320', '', '')
	
SELECT
	B.SUB_ORDER_ID,
	A.order_id,
	A.service_id,
	A.order_type,
	B.sub_order_state AS SOS,
	B.state_reason,
	A.CHANNEL AS CH,
	DATE_FORMAT(A.created_date, "%Y-%m-%d %H:%i") AS created_date
FROM
	COM_ORDER_MASTER PARTITION(p6) A
JOIN COM_SUB_ORDER_DETAILS PARTITION(p6) B ON
	A.ORDER_ID = B.ORDER_ID
WHERE
	B.state_reason='500 :: Error in calling getdata Account to get E164 for account balance : Contact ESB :: NCC'
	AND A.order_type IN ('AddSubscription','MpesaBundlePurchase')
	AND A.CREATED_DATE BETWEEN '2024-06-06 21:30:00' and '2024-06-07 06:30:00'
ORDER BY B.state_reason DESC;

SELECT
B.SUB_ORDER_ID,
	A.order_id,
	B.service_id,
	A.order_type,
FROM
	COM_ORDER_MASTER PARTITION(p6) A,
	COM_SUB_ORDER_DETAILS PARTITION(p6) B
WHERE
	A.ORDER_ID = B.ORDER_ID
	and B.SUB_ORDER_STATE != 'Completed'
	AND A.ORDER_ID IN ('1252209357768380416', '1247270427167526912', '1248961262901821440')
	
SELECT
	COUNT(*),
	ORDER_STATE
FROM
	COM_ORDER_MASTER PARTITION(p6)
WHERE
	ORDER_STATE != 'Failed'
	AND CREATED_DATE>'2024-06-21 20:10:00'
GROUP BY
	ORDER_STATE;
SELECT COUNT(*), ORDER_STATE FROM COM_ORDER_MASTER PARTITION(p6) WHERE ORDER_STATE != 'Failed' AND CREATED_DATE>'2024-06-21 20:10:00' GROUP BY ORDER_STATE;
---
WHERE
Mdn_series = 53
AND Account_Id = 251700494353
AND (Event_Result = '1')
AND Call_Start_Time between '2024-06-01 00:00:00' AND '2024-06-19 16:05:30'
ORDER BY CALL_START_TIME

select APINAME,count(*) from APIGW_RPT where DATE(PROCESS_DATE)=DATE(CURRENT_DATE)-1 group by APINAME order by APINAME;

SELECT
    SUM(IF(ORDER_TYPE='addservice' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='addservice' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='addsubscription' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='addsubscription' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='cancelsubscription' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='cancelsubscription' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='changesim' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='changesim' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='onboarding' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='onboarding' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='StopAutoRenewal' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='StopAutoRenewal' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='UpdateLanguage' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='UpdateLanguage' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='AddServiceToNewAccount' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='AddServiceToNewAccount' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='AdjustMainAccount' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='AdjustMainAccount' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='BlockVoucher' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='BlockVoucher' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='BookDeposit' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='BookDeposit' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='ChangeSubscription' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='ChangeSubscription' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='CreateDocument' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='CreateDocument' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='CreateIdentification' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='CreateIdentification' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='DeviceBlacklistWhitelist' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='DeviceBlacklistWhitelist' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='Gifting' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='Gifting' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='HardBarring' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='HardBarring' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='LifeCycleSync' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='LifeCycleSync' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='LifeCycleSyncTermination' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='LifeCycleSyncTermination' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='LineBarring' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='LineBarring' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='LineUnBarring' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='LineUnBarring' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='LockMpesa' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='LockMpesa' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='MakePayment' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='MakePayment' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='MoveToFWA' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='MoveToFWA' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='NumberRecycle' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='NumberRecycle' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='ResumeService' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='ResumeService' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='SuspendService' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='SuspendService' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='TransferOfService' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='TransferOfService' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='UpdateBucket' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='UpdateBucket' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='UpdateProfile' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='UpdateProfile' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='UnlockMpesa' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='UnlockMpesa' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='UpdateCreditLimit' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='UpdateCreditLimit' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='UpdateService' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='UpdateService' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`,
    SUM(IF(ORDER_TYPE='VoucherRecharge' and ORDER_STATE = "Completed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `COMPLETED`,
    SUM(IF(ORDER_TYPE='VoucherRecharge' and ORDER_STATE = "Failed" AND DATE(ORDER_DATE)>='2024-07-03' AND DATE(ORDER_DATE)<'2024-07-04', 1,0)) AS `FAILED`
FROM `COM_ORDER_MASTER`

SELECT DATE(ORDER_DATE) AS Ordered_Date, ORDER_STATE,ORDER_TYPE, COUNT(*)
FROM COM_ORDER_MASTER
WHERE ORDER_TYPE IN ('Onboarding','Addservice','AddServiceToNewAccount','AddSubscription','BlockVoucher','BookDeposit','AdjustMainAccount','CancelSubscription','ChangeSim','ChangeSubscription','CreateDocument','CreateIdentification','Gifting','HardBarring','LifeCycleSync','LifeCycleSyncTermination','LineBarring','LineUnBarring','MakePayment','MoveToFWA','NumberRecycle','ResumeService''StopAutoRenewal','SuspendService','TransferOfService','UpdateBucket','UpdateCreditLimit','UpdateLanguage','UpdateProfile','UnlockMpesa','UpdateService','DeviceBlacklistWhitelist','VoucherRecharge')
AND ORDER_STATE IN ('Failed', 'Completed')
AND DATE(ORDER_DATE) >= '2024-07-03'
AND DATE(ORDER_DATE) < '2024-07-04'
GROUP BY DATE(ORDER_DATE), ORDER_STATE,ORDER_TYPE

SELECT ORDER_TYPE,ORDER_STATE,count(*)from COM_ORDER_MASTER PARTITION(p7) where DATE(CREATED_DATE)=date(now())-1 and ORDER_STATE in ('Completed','Failed')  group by ORDER_TYPE,ORDER_STATE  order by ORDER_TYPE

SELECT
    ORDER_TYPE,
    ORDER_STATE,
---    SUM(CASE
---            WHEN ORDER_STATE = "Completed" THEN 1
---            ELSE 0
---        END) AS `COMPLETED`,
    SUM(CASE
            WHEN ORDER_STATE = "Failed" THEN 1
            ELSE 0
        END) AS `FAILED`
FROM `COM_ORDER_MASTER`
GROUP BY ORDER_TYPE, ORDER_STATE

SELECT DATE(ORDER_DATE) AS ORDERED_DATE, ORDER_STATE,ORDER_TYPE, COUNT(*) AS COUNT
FROM COM_ORDER_MASTER
WHERE ORDER_TYPE IN ('Onboarding','Addservice')
AND ORDER_STATE IN ('Failed', 'Completed')
AND ORDER_DATE >= '2024-07-09'
AND ORDER_DATE < '2024-07-10'
GROUP BY ORDERED_DATE, ORDER_STATE,ORDER_TYPE

WHERE ORDER_TYPE IN ('Onboarding','Addservice','AddServiceToNewAccount','AddSubscription','BlockVoucher','BookDeposit','AdjustMainAccount','CancelSubscription','ChangeSim','ChangeSubscription','CreateDocument','CreateIdentification','Gifting','HardBarring','LifeCycleSync','LifeCycleSyncTermination','LineBarring','LineUnBarring','MakePayment','MoveToFWA','NumberRecycle','ResumeService''StopAutoRenewal','SuspendService','TransferOfService','UpdateBucket','UpdateCreditLimit','UpdateLanguage','UpdateProfile','UnlockMpesa','UpdateService','DeviceBlacklistWhitelist','VoucherRecharge')
