SELECT A.ORDER_ID ,B.SUB_ORDER_ID, B.service_id,A.order_type,B.sub_order_state,B.state_reason,B.FAILED_STAGE_CODE, A.created_date,A.CHANNEL FROM COM_ORDER_MASTER PARTITION(p6) A, COM_SUB_ORDER_DETAILS PARTITION(p6) B
WHERE B.SUB_ORDER_STATE!='Completed' AND A.ORDER_TYPE IN ('MpesaBundlePurchase') AND  B.FAILED_STAGE_CODE IN ('MPESA_BUNDLE_REVERSAL','BUNDLE_REVERSAL_CALLBACK') AND A.CREATED_DATE AND A.CREATED_DATE BETWEEN '2024-06-01 06:30:00' and '2024-06-06 23:59:00'  AND A.ORDER_ID=B.ORDER_ID ORDER BY A.CREATED_DATE DESC;

Query for MPESA failed at the reversal stage 

SELECT A.order_id, B.SUB_ORDER_ID, B.service_id, A.order_type, B.sub_order_state, B.state_reason, A.created_date, A.CHANNEL
FROM COM_ORDER_MASTER A, COM_SUB_ORDER_DETAILS B
WHERE B.SUB_ORDER_STATE = 'Failed'
  AND A.ORDER_TYPE IN ('Onboarding', 'AddService')
  AND (B.STATE_REASON IN ('404 :: null :: NCC')
       OR B.STATE_REASON LIKE '400 :: Failed to provision%')
  AND A.CREATED_DATE BETWEEN DATE_SUB(NOW(), INTERVAL 10 DAY) AND NOW()
  AND A.ORDER_ID = B.ORDER_ID
ORDER BY A.CREATED_DATE DESC;